spring.application.name=laelops

spring.datasource.url=jdbc:postgresql://localhost:5432/laelops
spring.datasource.username=laelops
spring.datasource.password=laelops

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
